### PR TITLE
feat: handle job event by specified job name.

### PR DESCRIPTION
**Pull request by callmez**
see #165

### CODE REVIEW

**Comment by callmez** [comment]
@fwoelffel  can you check this PR?

**Comment by fwoelffel** [comment]
Sure @callmez 
I've already had a peek on it. Thanks for working on this so quickly :rocket: 

Could you also make this work with global events? I think there's a difference with the local events: the handler only gets the job id and not the job object.

**Comment by callmez** [comment]
it means `@OnGlobalQueueCompleted({ id: 'xxx' })`?  right?

**Comment by fwoelffel** [comment]
@callmez Not exactly, the decorator should expect a job name and not a job id.

The difference is that global event listeners don't get the job instance but only its id. See https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#global-events
One way to handle things would be to fetch the job instance when the event is a global one. See https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetjob

**Comment by callmez** [comment]
I know, i think we keep global event simple, just handle local event by name or id. what do you think?

**Comment by callmez** [comment]
Hi @fwoelffel, also can make global event work,  but it will cause different args. 
```js
@OnGlobalQueueCompleted({ name: '' })
onGlobalTestJobCompleted(job: Job) {
}
@OnGlobalQueueCompleted()
onGlobalJobCompleted(jobId) {
}
```

**Comment by fwoelffel** [comment]
Hi @callmez I'm glad that your helping me with this package 🙂 

How about the following:
```ts
@OnGlobalQueueCompleted({ name: string; getJob: boolean = false })
onGlobalTestJobCompleted(jobOrJobId: Job | string) {
}
```

The handler would only get the job instance if we passed `{ getJob: true }` to the decorator. This way, we get the original behavior by default and avoid any breaking change.

**Comment by callmez** [comment]
hi @fwoelffel , Could you please take a look, cause i really need it.

**Comment by fwoelffel** [comment]
Hi @callmez 
Sorry, I've been pretty busy for the last days. I've reviewed your PR and everything seems fine except one thing:
```js
export type BullQueueEventOptions = RequireOnlyOne<
  {
    eventName: BullQueueEvent;
    name?: string;
    id?: string;
  },
  'id' | 'name'
>;

export type QueueEventDecoratorOptions = RequireOnlyOne<
  { id?: string; name?: string },
  'id' | 'name'
>;
```

What is the usecase for the `id`? I mean, handling job based on their name is cool, but what would be the point to add a listener for a single given job id?
Don't you think you could remove the `id` property from those type and also update the `BullExplorer.handleListener` method so it doesn't look for the `id`?

**Comment by callmez** [comment]
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

Unique Job is very useful for me.
it means I can add one-time jobs without worrying about duplicates, so I need handle it by JobId.

**Comment by callmez** [comment]
thanks！👍

**Pull request merged**
